### PR TITLE
Provide specific external for library type.

### PR DESCRIPTION
**Pull request by simonjwright**
* gpr/gpr.gpr (Gnat_Lib_Type): new external GPR_LIBRARY_TYPE, acts as the default for LIBRARY_TYPE.

### CODE REVIEW

**Comment by t-14** [comment]
Can you clarify what are you trying to do here? Creating the deputy environment variable at the point of the build project doesn't seem to make much sense, and once the project is gprinstall-ed it will get the env variable pair automatically...

**Comment by simonjwright** [comment]
To avoid name collision for scenario variables, as in fb04bce.

I had thought this was a general change adopted by AdaCore, but I see it’s not (the equivalent is in at least the langkit_support, libadalang and gpr2 project files).

Found the issue building gnatdoc under Alire (I ended up just setting `LIBRARY_TYPE` to `relocatable`).

**Comment by t-14** [comment]
But you _aren't_ avoiding name collision. Your primary env variable is still LIBRARY_TYPE. The patch that you mention does it in the opposite order.

**Comment by simonjwright** [comment]
Closing, because actually implemented in 5790e77.

**Pull request closed without merging**
