### PR TITLE
Suggestions gathered from Debian.

### PR DESCRIPTION
**Pull request by asarhaddon**
Hello.
I think that a github pull request is now the recommended way to suggest changes for gprbuild.
Each commit contains a separate suggestion. I may split the PRi if this fits your workflow better.
Thanks for considering.

### CODE REVIEW

**Comment by t-14** [comment]
Thank you for your contribution. May I ask you to spin off into two separate PRs the following two commits: "Move PIC/shared options later on the command line for libraries" and "Fix and simplify build of static libraries" as those are relatively involved so we prefer to double-check them internally before approving. Thanks in advance.

**Comment by asarhaddon** [comment]
Hi. I have split the merge request.

**Comment by asarhaddon** [comment]
Hi. A rebase has been necessary because a recent commit on master was duplicated work. I have removed the related patch from the queue.

**Comment by asarhaddon** [comment]
I have moved each commit into its own merge request, hopefully reducing the work to rebase after the split of gprconfig_kb.

**Pull request closed without merging**
